kind: List
apiVersion: v1
items:

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhel7-weblogic:v12.2.1
    source:
      type: Git
      git:
        uri: https://github.com/rbaumgar/OracleWebLogic.git
      contextDir: 12.2.1
    strategy:
      dockerStrategy:
        env:
        - name: FMW_BASEURL
          value: http://caddy-abc.192.168.122.111.xip.io
        - name: FMW_VERSION
          value: 12.2.1.2.0
        - name: FMW_QUICK
          value: "True"
        from:
          kind: ImageStreamTag
          name: rhel7-oraclejdk:v1.8.0
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
